### ISSUE TITLE
newCluster() broken code

### ISSUE THREAD

**Issue by mattes** [gambol99/go-marathon#104]
https://github.com/gambol99/go-marathon/blob/master/cluster.go#L90

`newCluster()` should first split by commas and then do the `url.Parse()`. I'm surprised that url.Parse isn't failing anyway. The marathon variables holds:

```
&url.URL{Scheme:"http", Opaque:"", User:(*url.Userinfo)(nil), Host:"10.241.1.71:8080,10.241.1.72:8080,10.241.1.73:8080", Path:"", RawPath:"", RawQuery:"", Fragment:""}
```

... and `Host` doesn't look like a valid host to me.

**Comment by gambol99** [comment]
@mattes agreed! ... we should validate each one ... I'll raise a PR

**Comment by timoreimann** [comment]
@gambol99 Are you working on this one? Otherwise, I'd like to take a stab.

**Comment by timoreimann** [comment]
After a bit of investigation, I don't think we need to make any significant changes. Specifically,

1. The parsed `Host` field is [already split on comma](https://github.com/gambol99/go-marathon/blob/master/cluster.go#L104), so we're not using the comma-separated list directly. Parsing the `marathonURL` passed to `newCluster` still makes sense though since the schema needs to be (and is) verified.
1. Applying `url.Parse()`/`url.ParseRequestURI()` on each host doesn't really add a lot of value: The main job of the methods is to parse the schema and host, retrieve authorization data, and do unescaping. We already do the first one on `marathonURL` and don't really care about the latter two as the contained hosts will eventually be used in a request to Marathon as-is. (Side note: To me it seems that Golang's parsing functions are mainly for parsing URLs structurally, not validation.)

The only thing I'd recommend at this stage is to check for empty hosts. WDYT?

**Comment by timoreimann** [comment]
I put together a PR based on my observations/assumptions pro-actively. Happy to discuss. :)
