### ISSUE TITLE
Odd Error object issue

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#151]
My app was having Marathon connectivity issues and unexpectedly panicked when using the `err` object  returned by `client.CreateApplication`.

My code:

```
        _, err := m.Client.CreateApplication(application)
	if err != nil {
		log.Error(err)
		if err.Error() == ErrClusterConnectivity.Error() {
			m.resetClient()
		}
      }
```

The call to `log.Error(err)` prints '`<nil>`' and the call to `err.Error()` panics with a null pointer exception. Since this is all wrapped by `if err != nil`, it feels like the err object returned by `.CreateApplication` (https://github.com/gambol99/go-marathon/blob/master/application.go#L538) might be improperly initialized.

This the actual line that causes the panic:  https://github.com/gambol99/go-marathon/blob/master/error.go#L55

Any idea what's going on here?

**Comment by timoreimann** [comment]
The problem is likely within [error.go](https://github.com/gambol99/go-marathon/blob/52466f39391c90839b2a75715d5c5af68b7e7502/error.go). I already found one issue (#152) while going through the code; however, I don't think it's related to your case.

Will dig deeper tomorrow. In the meantime, could you tell me what version of Marathon you are using? Are you running on the latest go-marathon HEAD version? And is there a way for you to reproducible trigger the error?

Thanks for reporting!

**Comment by iderdik** [comment]
Marathon version is v.15.1. I'm not on the latest version of go-marathon but not too old  (sha: 9cbc78ff19ebab78a7ad78e2f2be310d81775c79). Subsequent commits did not seem to deal with this area.

I can't reproduce this reliably at all :(. I have noticed it seems to happen when Marathon is unhappy and showing a `503` error when accessing the UI. Hope this helps!

**Comment by timoreimann** [comment]
Turned out that the bug filed under #152 is in fact the culprit for the problem described. (See also [my comment](https://github.com/gambol99/go-marathon/issues/152#issuecomment-223773440) on the issue.) Will try to put together a fix soonish.

**Comment by timoreimann** [comment]
@iderdik problem should hopefully be fixed now. If not, please reopen this issue or create a new one, whatever you deem more appropriate.

Thanks!

**Comment by iderdik** [comment]
Awesome - I'll give it a try and report back here. Thanks for the quick resolution!
