### ISSUE TITLE
Marathon application schema changes.

### ISSUE THREAD

**Issue by dmajere** [gambol99/go-marathon#171]
`taskKillGracePeriodSeconds` field was added to marathon application struct.
Documentation about it can be found here - https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/mesosphere/marathon/api/v2/AppsResource_create.md

Also `secrets` field was added, but i can't find any documentation about it right now, its only mentioned in schema - https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/schema/AppDefinition.json

**Comment by timoreimann** [comment]
Both fields are related to PRs assigned to milestone 1.3. Since Mesosphere has decided to skip 1.2, I think we can expect the next stable release to include proper documentation.

I'd rather wait to add support for either in go-marathon until the features truly end up in the next stable release. Happy to review any PRs of yours though once things have landed.

**Comment by timoreimann** [comment]
Support for the task kill grace period has been added by now.

**Comment by timoreimann** [comment]
#299 brought support for secrets. This issue is resolved.
