### ISSUE TITLE
Failover to other nodes in a Marathon cluster not working during event subscription

### ISSUE THREAD

**Issue by sybrandy** [gambol99/go-marathon#212]
So, we recently had an issue where one of our Marathon nodes was "up", but inaccessible.  Unfortunately, our code thought Marathon was down and crashed.  Looking at the logs, it looks like the AddEventListener attempted to connect to the same node several times (we use a retrier) instead of trying different nodes.  It would be better if it would attempt to connect to a different node.  A few thoughts:
1. GetMember is refactored so that it round-robins through all of the nodes regardless of whether or not the node is up or down.
2. Refactor the subscription code so that if there is an error connecting, it marks the node as down after N attempts.
3. Combine both solutions to round-robin requests between nodes and mark nodes as down if there are multiple failures when attempting to connect to them.

Right now, I have to remove the node from the config until the node comes back up.

**Comment by gambol99** [comment]
hi @sybrandy  ... so just to be clear, essentially the marathon instance was responding to a /ping but ultimately not functioning? ...

**Comment by timoreimann** [comment]
@gambol99 looking at the cluster code, I get the feeling that it's not doing what we expect it to do: `GetMember()` essentially [iterates through all nodes and returns the first one considered up](https://github.com/gambol99/go-marathon/blob/8908223430b37fc4106d8b8cf1f38cf7124020f1/cluster.go#L167-L170). However, we only seem to start marking nodes as down (and retrying them for liveness again) [if we have no more up nodes remaining](https://github.com/gambol99/go-marathon/blob/8908223430b37fc4106d8b8cf1f38cf7124020f1/cluster.go#L180). Looks like a chicken-and-egg problem.

I think what we should do instead is feed the result of a failing Marathon request back into the cluster, marking it as down, and trying with another host. Alternatively, we could `/ping` each host first, though that would involve an extra round trip and require some more refactoring because things like [DCOS-specific hostnames are not taken into consideration](https://github.com/gambol99/go-marathon/blob/8908223430b37fc4106d8b8cf1f38cf7124020f1/client.go#L258-L259) by `MarkDown()`.

WDYT?

**Comment by sybrandy** [comment]
@gambol99 it couldn't have been responding to a /ping because, in this case, the marathon port was blocked by a firewall.  I think the other marathon nodes recognized it as being there because it was still in Zookeeper, which somehow maintained quorum.

**Comment by gambol99** [comment]
@timoreimann ... yeah, i see what you mean in the cluster.go code. ... Feels somewhat hacky, but since every request is funneled via apiRequest we could loop it;

```shell
for member = getmember() != nil
 response, err = make_request
 if err != nil  {
   switch err 
   case timeout
     member.markdown()
     # try again
     continue
   default: 
     # handle error as per normal
     return newAPIError(err)  
 }

 return result   
done

return no_members
```

**Comment by timoreimann** [comment]
The loop should work; we just need to make sure that  we cover all error paths. Besides timeouts, there's also connection errors and 5xx responses. And we probably need to synchronize the retry goroutine and the part in `cluster.go` referencing the active node set.

As soon as I find some time I'll take a stab. Let me know if you want to tackle it first though.

**Comment by gambol99** [comment]
@timoreimann ... i'm happy to take a look this weekend ...

**Comment by timoreimann** [comment]
@gambol99 Sounds good. Happy to review any patches you may send it!

**Comment by timoreimann** [comment]
@gambol99 did you have a chance to work on a fix yet? I can also try to take a stab, though it'll likely take me another week before I can carve out some time.

**Comment by gambol99** [comment]
hi @timoreimann, thank you for reminding me!! .. I've the memory for a goldfish! ... I've whipped something up now. The PR is https://github.com/gambol99/go-marathon/pull/231 .. Could definitely use you review though

**Comment by timoreimann** [comment]
Great -- will try to have a look tonight!

**Comment by timoreimann** [comment]
#231 addressed the problem for regular, non-subscription traffic. Updated the title to be more specific for event subscriptions.

**Comment by gambol99** [comment]
I'll raise a PR to fix this one shortly

**Comment by timoreimann** [comment]
Hey @gambol99, it's been a while we touched on this issue.

Do you still plan on providing a fix for this?

**Comment by guilhem** [comment]
We experiment same problem on production (with `traefik`).
First node (in list) was on failure state: instances wasn't updated and on restart subscription never fallback to other masters (up and running).

**Comment by marco-jantke** [comment]
I am currently having a look into this as it is relevant for our production setup. Anyway I will be occupied most of next week, so not sure when I can deliver something. So let me know when $you also start to work on this issue.

**Comment by timoreimann** [comment]
This should be fixed now.
