### ISSUE TITLE
DeleteApplication fails with "Marathon API Error: "

### ISSUE THREAD

**Issue by iderdik** [gambol99/go-marathon#268]
I seem to have this intermittent issue where calling DeleteApplication fails with the error `"Marathon API error: "` and no additional info. Nothing appears in the Marathon logs. 

I'm using Marathon 1.3.0 and Mesos 1.0.1.

Have you encountered this issue at all?

**Comment by timoreimann** [comment]
Thanks for the report @iderdik.

The problem is that the error message cannot be parsed anymore. I suppose that Mesosphere has changed the structure of the error JSON response (once again).

Do you have a chance to initialize your go-marathon client with the [LogOutput](https://github.com/gambol99/go-marathon/blob/1bdd2f857d78ffcd3b24cb9131f5abb6e01885c0/config.go#L50) parameter set to `os.Stdout`? That way, we should [see the response body](https://github.com/gambol99/go-marathon/blob/1bdd2f857d78ffcd3b24cb9131f5abb6e01885c0/client.go#L292-L296).

**Comment by iderdik** [comment]
@timoreimann I can't get that level of detail turned on in the system I'm seing this with. However, combing through Marathon logs, I do see the DELETE calling returning a `405` error if that helps.

**Comment by iderdik** [comment]
And I've actually figured the error out (I think). When we inadvertently send a blank Marathon app name to `DeleteApplication` (due to a logic error on my side), this error occurs (with the blank message). Better error handling/condition checking would definitely help here - I'll try to open a PR if  I have some time.

**Comment by timoreimann** [comment]
Thanks for investigating.

The problem is that we currently [do not encode 405s](https://github.com/gambol99/go-marathon/blob/48f66461ea089ac5f96f0c72e43c0b2acef8e7c2/error.go#L26-L45). The fix is to unmarshal such errors into a dedicated type.

Additionally, we should fall back to showing just the pure JSON content if we can't map the error any better.
