### ISSUE TITLE
Marathon hosts marked as down never become healthy with Marathon 1.4.4

### ISSUE THREAD

**Issue by willgorman** [gambol99/go-marathon#308]
We've noticed an issue using go-marathon with Marathon 1.4.4 (as part of DC/OS 1.9.2) where we end up in a state where every call to the Marathon API fails and logs "all the Marathon hosts are presently down", despite the Marathon endpoints being reachable and healthy.  I believe this is related to a [change in Marathon 1.4.4](https://github.com/mesosphere/marathon/pull/5380) that causes the `/ping` API to return a `406` when called with the header `Accept: application/json`.  Consequently, whenever go-marathon marks a host as down and checks on it by [calling `/ping` until it gets a `200`](https://github.com/gambol99/go-marathon/blob/e1af3386c5421ba87a73b6a80b13330645f10ea5/cluster.go#L131) this will cause it to get a `406` every time and never mark that host as up again.

**Comment by timoreimann** [comment]
@willgorman thanks for reporting.

If previous versions of Marathon return a proper response on the ping handler even without the Accept header set to JSON, I suppose we can just change go-marathon accordingly. Otherwise, we'll have to resort to something like sending two different requests to `/ping` and see if any returns 200.

**Comment by iderdik** [comment]
+1

**Comment by timoreimann** [comment]
@willgorman this should now be fixed. could you try again with the latest master?
